add_library(sdurws_ird_core STATIC src/Core.cpp)
target_include_directories(sdurws_ird_core PUBLIC include)
target_link_libraries(sdurws_ird_core PUBLIC sdurw_math)
add_library(sdurws_ird_testkit INTERFACE)
target_link_libraries(sdurws_ird_testkit INTERFACE sdurws_ird_core)
add_executable(sdurws_ird_core_test test_main.cpp)
target_link_libraries(sdurws_ird_core_test PRIVATE sdurws_ird_core GTest::gtest_main)
add_library(sdurws_ird_kinematics INTERFACE)
target_include_directories(sdurws_ird_kinematics INTERFACE include)
