#include "RobotModelSpecJson.hpp"
#include "RobotModelFingerprint.hpp"
#include "RobotModelProjectPaths.hpp"
#include "RobotModelXmlWriter.hpp"

#include <QDir>
#include <QFile>
#include <QFileInfo>
#include <QJsonArray>
#include <QJsonDocument>
#include <QJsonObject>
#include <QProcess>
#include <QTemporaryDir>

#include <cmath>
#include <cstdlib>
#include <iostream>
#include <string>

// 浮点近似比较
static bool nearlyEqual (double a, double b, double eps = 1e-12)
{
    return std::fabs (a - b) <= eps;
}

static int fail (const std::string& msg)
{
    std::cerr << "FAIL: " << msg << std::endl;
    return 1;
}

class CurrentDirectoryGuard
{
  public:
    CurrentDirectoryGuard () : _original (QDir::currentPath ()) {}
    ~CurrentDirectoryGuard () { QDir::setCurrent (_original); }

  private:
    QString _original;
};

static bool writeBytes (const QString& path, const QByteArray& bytes = QByteArray ("mesh"))
{
    if (!QDir ().mkpath (QFileInfo (path).absolutePath ()))
        return false;
    QFile file (path);
    return file.open (QIODevice::WriteOnly | QIODevice::Truncate) &&
           file.write (bytes) == bytes.size ();
}

static bool copyFile (const QString& source, const QString& target)
{
    return QDir ().mkpath (QFileInfo (target).absolutePath ()) && QFile::copy (source, target);
}

static bool isInsideProject (const QString& path, const QString& projectRoot)
{
    const QString relative = QDir (QFileInfo (projectRoot).absoluteFilePath ()).relativeFilePath (
        QFileInfo (path).absoluteFilePath ());
    return relative != QStringLiteral ("..") &&
           !relative.startsWith (QStringLiteral ("../")) && !QDir::isAbsolutePath (relative);
}

// 深层比较两个 RobotModelSpec 的所有字段
static bool sameRobotModelSpec (const rws::RobotModelSpec& a, const rws::RobotModelSpec& b)
{
    if (a.robotName != b.robotName) return false;
    if (a.saveDirectory != b.saveDirectory) return false;
    if (a.mode != b.mode) return false;
    if (a.exportDhJointsAdvanced != b.exportDhJointsAdvanced) return false;
    if (a.showFrameAxes != b.showFrameAxes) return false;
    if (a.generateDrawables != b.generateDrawables) return false;
    if (a.generateScene != b.generateScene) return false;
    if (a.imported.active != b.imported.active) return false;
    if (a.imported.sourceSceneFile != b.imported.sourceSceneFile) return false;
    if (a.imported.sourceDeviceFile != b.imported.sourceDeviceFile) return false;
    if (a.imported.sourceCollisionSetupFile != b.imported.sourceCollisionSetupFile) return false;
    if (a.imported.sourceProximitySetupFile != b.imported.sourceProximitySetupFile) return false;
    if (a.imported.workcellExtensions != b.imported.workcellExtensions) return false;
    if (a.imported.deviceExtensions != b.imported.deviceExtensions) return false;
    if (a.exportLayout.deviceFile != b.exportLayout.deviceFile) return false;
    if (a.exportLayout.sceneFile != b.exportLayout.sceneFile) return false;
    if (a.exportLayout.dynamicWorkCellFile != b.exportLayout.dynamicWorkCellFile) return false;
    if (a.exportLayout.collisionSetupFile != b.exportLayout.collisionSetupFile) return false;
    if (a.exportLayout.proximitySetupFile != b.exportLayout.proximitySetupFile) return false;
    if (a.exportLayout.preserveImportedFileLayout != b.exportLayout.preserveImportedFileLayout)
        return false;

    // robotBaseFrame
    if (a.robotBaseFrame.name != b.robotBaseFrame.name) return false;

    // sceneFrames
    if (a.sceneFrames.size () != b.sceneFrames.size ()) return false;
    for (std::size_t i = 0; i < a.sceneFrames.size (); ++i) {
        if (a.sceneFrames[i].name != b.sceneFrames[i].name) return false;
    }

    // transformJoints
    if (a.transformJoints.size () != b.transformJoints.size ()) return false;
    for (std::size_t i = 0; i < a.transformJoints.size (); ++i) {
        if (a.transformJoints[i].name != b.transformJoints[i].name) return false;
        for (int j = 0; j < 3; ++j) {
            if (!nearlyEqual (a.transformJoints[i].pos[j], b.transformJoints[i].pos[j]))
                return false;
        }
    }

    // drawables
    if (a.drawables.size () != b.drawables.size ()) return false;
    for (std::size_t i = 0; i < a.drawables.size (); ++i) {
        if (a.drawables[i].name != b.drawables[i].name) return false;
        if (a.drawables[i].autoGenerated != b.drawables[i].autoGenerated) return false;
    }

    // collisionModels
    if (a.collisionModels.size () != b.collisionModels.size ()) return false;
    for (std::size_t i = 0; i < a.collisionModels.size (); ++i) {
        if (a.collisionModels[i].enabled != b.collisionModels[i].enabled) return false;
    }

    // limits
    if (a.limits.size () != b.limits.size ()) return false;

    // poses
    if (a.poses.size () != b.poses.size ()) return false;

    // dynamics
    if (a.dynamics.links.size () != b.dynamics.links.size ()) return false;
    if (a.dynamics.forceLimits.size () != b.dynamics.forceLimits.size ()) return false;

    // includes
    if (a.includes.size () != b.includes.size ()) return false;

    // collisionSetup
    if (a.collisionSetup.enabled != b.collisionSetup.enabled) return false;
    if (a.collisionSetup.excludeBaseToFirstJoint != b.collisionSetup.excludeBaseToFirstJoint)
        return false;
    if (a.collisionSetup.excludePairs.size () != b.collisionSetup.excludePairs.size ())
        return false;
    for (std::size_t i = 0; i < a.collisionSetup.excludePairs.size (); ++i) {
        if (a.collisionSetup.excludePairs[i].enabled !=
            b.collisionSetup.excludePairs[i].enabled) return false;
        if (a.collisionSetup.excludePairs[i].source !=
            b.collisionSetup.excludePairs[i].source) return false;
        if (a.collisionSetup.excludePairs[i].reason !=
            b.collisionSetup.excludePairs[i].reason) return false;
    }

    // proximitySetup
    if (a.proximitySetup.enabled != b.proximitySetup.enabled) return false;

    // sceneGeometries
    if (a.sceneGeometries.size () != b.sceneGeometries.size ()) return false;

    // dhJoints
    if (a.dhJoints.size () != b.dhJoints.size ()) return false;

    return true;
}

static int testFullRoundTrip ()
{
    rws::RobotModelSpec original =
        rws::RobotModelXmlWriter::makeDefaultSixAxisModel (QDir::tempPath ());
    original.robotName = "JsonRoundTrip";
    if (!original.collisionModels.empty ()) {
        original.collisionModels.front ().enabled = false;
    }
    rws::FramePairSpec pair;
    pair.first = "Joint1";
    pair.second = "Joint3";
    pair.enabled = false;
    pair.source = "Manual";
    pair.reason = "Round-trip disabled pair";
    original.collisionSetup.excludeBaseToFirstJoint = false;
    original.collisionSetup.excludePairs.push_back (pair);
    original.proximitySetup.enabled = true;
    original.proximitySetup.rules.push_back (
        {rws::ProximityRuleKind::Exclude, "Joint.*", "Tool.*"});
    original.imported.active = true;
    original.imported.sourceSceneFile = "CustomScene.wc.xml";
    original.imported.sourceDeviceFile = "vendor/Robot.wc.xml";
    original.imported.sourceCollisionSetupFile = "vendor/CollisionSetup.xml";
    original.imported.sourceProximitySetupFile = "vendor/ProximitySetup.xml";
    original.exportLayout.preserveImportedFileLayout = true;
    original.exportLayout.deviceFile = "export/JsonRoundTrip.wc.xml";
    original.exportLayout.sceneFile = "export/JsonRoundTripScene.wc.xml";
    original.exportLayout.dynamicWorkCellFile = "export/JsonRoundTrip.dwc.xml";
    original.exportLayout.collisionSetupFile = "export/CollisionSetup.xml";
    original.exportLayout.proximitySetupFile = "export/ProximitySetup.xml";
    original.imported.workcellExtensions.push_back (
        "<ImportedExtension semantic=\"keep\" />");
    original.imported.deviceExtensions.push_back (
        "<VendorDeviceData value=\"preserve\" />");

    const std::string json = rws::RobotModelSpecJson::toJson (original);
    rws::RobotModelSpec decoded;
    std::string error;
    if (!rws::RobotModelSpecJson::fromJson (json, decoded, &error))
        return fail ("RobotModelSpec JSON round trip failed: " + error);
    if (!sameRobotModelSpec (original, decoded))
        return fail ("RobotModelSpec JSON round trip changed at least one field.");
    return 0;
}

static int testLegacyCollisionMetadataIsDiscardedOnSave ()
{
    rws::RobotModelSpec original =
        rws::RobotModelXmlWriter::makeDefaultSixAxisModel (QDir::tempPath ());
    rws::CollisionModelSpec collision;
    collision.name = "LegacyCollision";
    collision.refFrame = "Joint1";
    original.collisionModels.push_back (collision);

    QJsonObject legacy = rws::RobotModelSpecJson::toObject (original);
    QJsonArray drawables = legacy.value ("drawables").toArray ();
    QJsonObject drawable = drawables.at (0).toObject ();
    drawable["visualDetail"] = "Both";
    drawable["collisionModel"] = true;
    drawables[0] = drawable;
    legacy["drawables"] = drawables;

    QJsonArray collisionModels = legacy.value ("collisionModels").toArray ();
    QJsonObject collisionModel = collisionModels.at (0).toObject ();
    collisionModel["geometryDetail"] = "Fine";
    collisionModel["source"] = "Imported";
    collisionModels[0] = collisionModel;
    legacy["collisionModels"] = collisionModels;

    rws::RobotModelSpec decoded;
    std::string error;
    QJsonObject legacyRoot;
    legacyRoot["schemaVersion"] = 1;
    legacyRoot["type"] = "RobotModelSpec";
    legacyRoot["data"] = legacy;
    const std::string legacyJson = QJsonDocument (legacyRoot).toJson ().toStdString ();
    if (!rws::RobotModelSpecJson::fromJson (legacyJson, decoded, &error))
        return fail ("Legacy metadata JSON failed to load: " + error);

    const QJsonObject saved = rws::RobotModelSpecJson::toObject (decoded);
    const QJsonObject savedDrawable = saved.value ("drawables").toArray ().at (0).toObject ();
    const QJsonObject savedCollision =
        saved.value ("collisionModels").toArray ().at (0).toObject ();
    if (savedDrawable.contains ("visualDetail") || savedDrawable.contains ("collisionModel") ||
        savedCollision.contains ("geometryDetail") || savedCollision.contains ("source"))
        return fail ("Legacy collision presentation metadata was written back to JSON.");
    if (!savedCollision.value ("enabled").toBool ())
        return fail ("Collision model enabled state was not preserved.");
    return 0;
}

static int testDhAuthorityFlagIsPersistedAndLegacyDefaultsToFalse ()
{
    rws::RobotModelSpec original =
        rws::RobotModelXmlWriter::makeDefaultSixAxisModel (QDir::tempPath ());
    const QJsonObject serialized = rws::RobotModelSpecJson::toObject (original);
    if (!serialized.contains ("dhParametersAuthoritative"))
        return fail ("DH authority flag was not written to RobotModelSpec JSON.");

    rws::RobotModelSpec decoded;
    std::string error;
    if (!rws::RobotModelSpecJson::fromObject (serialized, decoded, &error))
        return fail ("DH authority JSON round trip failed: " + error);
    if (rws::RobotModelSpecJson::toObject (decoded)
            .value ("dhParametersAuthoritative")
            .toBool (true))
        return fail ("Default non-native DH model must not become authoritative.");

    QJsonObject legacy = serialized;
    legacy.remove ("dhParametersAuthoritative");
    rws::RobotModelSpec legacyDecoded;
    if (!rws::RobotModelSpecJson::fromObject (legacy, legacyDecoded, &error))
        return fail ("Legacy RobotModelSpec without DH authority flag failed: " + error);
    if (rws::RobotModelSpecJson::toObject (legacyDecoded)
            .value ("dhParametersAuthoritative")
            .toBool (true))
        return fail ("Legacy RobotModelSpec must default DH authority to false.");
    return 0;
}

static int testFingerprint ()
{
    rws::RobotModelSpec original =
        rws::RobotModelXmlWriter::makeDefaultSixAxisModel (QDir::tempPath ());
    const std::string originalDirectory = original.saveDirectory;
    const std::string fingerprint = rws::RobotModelFingerprint::canonicalSha256 (original);
    if (fingerprint.empty ())
        return fail ("Model fingerprint must not be empty.");

    rws::RobotModelSpec relocated = original;
    relocated.saveDirectory = QDir::homePath ().toStdString ();
    if (fingerprint != rws::RobotModelFingerprint::canonicalSha256 (relocated))
        return fail ("Model fingerprint must ignore saveDirectory.");

    relocated.transformJoints.at (1).pos[0] += 0.001;
    if (fingerprint == rws::RobotModelFingerprint::canonicalSha256 (relocated))
        return fail ("Model fingerprint must change for engineering content.");
    if (original.saveDirectory != originalDirectory)
        return fail ("Model fingerprint must not mutate the input model.");

    QTemporaryDir originalProject;
    QTemporaryDir movedProject;
    if (!originalProject.isValid () || !movedProject.isValid ())
        return fail ("Could not create project roots for portable fingerprint testing.");
    rws::RobotModelSpec managed = original;
    managed.saveDirectory =
        originalProject.filePath ("generated/robot-models").toStdString ();
    rws::DrawableSpec drawable;
    drawable.shape = "Mesh";
    drawable.filePath = originalProject.filePath ("assets/base.stl").toStdString ();
    managed.drawables = {drawable};
    const std::string managedFingerprint =
        rws::RobotModelFingerprint::canonicalSha256 (managed);
    rws::RobotModelSpec moved = managed;
    moved.saveDirectory = movedProject.filePath ("generated/robot-models").toStdString ();
    moved.drawables.front ().filePath = movedProject.filePath ("assets/base.stl").toStdString ();
    if (managedFingerprint != rws::RobotModelFingerprint::canonicalSha256 (moved))
        return fail ("Model fingerprint must survive a managed project directory move.");
    return 0;
}

static int testManagedProjectGeometryPathsArePortable ()
{
    QTemporaryDir originalProject;
    QTemporaryDir movedProject;
    QTemporaryDir hostileWorkingDirectory;
    if (!originalProject.isValid () || !movedProject.isValid () ||
        !hostileWorkingDirectory.isValid ())
        return fail ("Could not create temporary directories for project path tests.");

    const QString drawablePath = originalProject.filePath ("assets/visual/base.stl");
    const QString collisionPath = originalProject.filePath ("assets/collision/base.stl");
    const QString scenePath = originalProject.filePath ("assets/scene/table.stl");
    if (!writeBytes (drawablePath) || !writeBytes (collisionPath) || !writeBytes (scenePath))
        return fail ("Could not create managed geometry fixtures.");

    rws::RobotModelSpec runtime =
        rws::RobotModelXmlWriter::makeDefaultSixAxisModel (originalProject.path ());
    runtime.saveDirectory.clear ();
    runtime.drawables.clear ();
    runtime.collisionModels.clear ();
    runtime.sceneGeometries.clear ();

    rws::DrawableSpec drawable;
    drawable.name = "BaseVisual";
    drawable.shape = "Mesh";
    drawable.filePath = QFileInfo (drawablePath).absoluteFilePath ().toStdString ();
    runtime.drawables.push_back (drawable);

    rws::CollisionModelSpec collision;
    collision.name = "BaseCollision";
    collision.shape = "Mesh";
    collision.filePath = QFileInfo (collisionPath).absoluteFilePath ().toStdString ();
    runtime.collisionModels.push_back (collision);

    rws::SceneGeometrySpec scene;
    scene.name = "Table";
    scene.kind = rws::GeometryKind::Mesh;
    scene.file = QFileInfo (scenePath).absoluteFilePath ().toStdString ();
    runtime.sceneGeometries.push_back (scene);

    rws::RobotModelSpec portable;
    QString error;
    if (!rws::RobotModelProjectPaths::makePortable (
            runtime, originalProject.path (), portable, &error))
        return fail ("Could not make managed geometry paths portable: " +
                     error.toStdString ());
    const QByteArray json = QByteArray::fromStdString (rws::RobotModelSpecJson::toJson (portable));
    if (json.contains (QFileInfo (originalProject.path ()).absoluteFilePath ().toUtf8 ()))
        return fail ("Managed RobotModelBuilder JSON must not contain the original project root.");
    if (QDir::isAbsolutePath (QString::fromStdString (portable.drawables.front ().filePath)) ||
        QDir::isAbsolutePath (
            QString::fromStdString (portable.collisionModels.front ().filePath)) ||
        QDir::isAbsolutePath (QString::fromStdString (portable.sceneGeometries.front ().file)))
        return fail ("Every managed geometry field must be project-relative.");

    const QString movedDrawable = movedProject.filePath ("assets/visual/base.stl");
    const QString movedCollision = movedProject.filePath ("assets/collision/base.stl");
    const QString movedScene = movedProject.filePath ("assets/scene/table.stl");
    if (!copyFile (drawablePath, movedDrawable) || !copyFile (collisionPath, movedCollision) ||
        !copyFile (scenePath, movedScene))
        return fail ("Could not copy the managed project geometry fixtures.");

    CurrentDirectoryGuard cwdGuard;
    if (!QDir::setCurrent (hostileWorkingDirectory.path ()))
        return fail ("Could not establish a hostile process working directory.");

    rws::RobotModelSpec resolved;
    if (!rws::RobotModelProjectPaths::resolveManaged (
            portable, movedProject.path (), resolved, &error))
        return fail ("Could not resolve the moved managed model: " + error.toStdString ());
    const QString expectedOutputDirectory =
        movedProject.filePath ("generated/robot-models");
    if (QDir::cleanPath (QString::fromStdString (resolved.saveDirectory)) !=
        QDir::cleanPath (expectedOutputDirectory))
        return fail ("Managed model resolution must restore its runtime output directory.");
    if (!isInsideProject (QString::fromStdString (resolved.drawables.front ().filePath),
                          movedProject.path ()) ||
        !isInsideProject (QString::fromStdString (resolved.collisionModels.front ().filePath),
                          movedProject.path ()) ||
        !isInsideProject (QString::fromStdString (resolved.sceneGeometries.front ().file),
                          movedProject.path ()))
        return fail ("Resolved geometry must remain inside the moved project root.");
    if (QFileInfo (QString::fromStdString (resolved.drawables.front ().filePath)).absoluteFilePath () !=
            QFileInfo (movedDrawable).absoluteFilePath () ||
        QFileInfo (QString::fromStdString (resolved.collisionModels.front ().filePath))
                .absoluteFilePath () != QFileInfo (movedCollision).absoluteFilePath () ||
        QFileInfo (QString::fromStdString (resolved.sceneGeometries.front ().file))
                .absoluteFilePath () != QFileInfo (movedScene).absoluteFilePath ())
        return fail ("Managed geometry paths did not relocate with the project.");

    return 0;
}

static int testManagedProjectGeometryRejectsEscapes ()
{
    QTemporaryDir project;
    QTemporaryDir outside;
    if (!project.isValid () || !outside.isValid ())
        return fail ("Could not create temporary directories for path rejection tests.");

    const QString outsideMesh = outside.filePath ("outside.stl");
    if (!writeBytes (outsideMesh))
        return fail ("Could not create an outside-project geometry fixture.");

    rws::RobotModelSpec runtime;
    rws::DrawableSpec drawable;
    drawable.shape = "Mesh";
    drawable.filePath = QFileInfo (outsideMesh).absoluteFilePath ().toStdString ();
    runtime.drawables.push_back (drawable);

    rws::RobotModelSpec untouched;
    untouched.robotName = "untouched";
    QString error;
    if (rws::RobotModelProjectPaths::makePortable (runtime, project.path (), untouched, &error))
        return fail ("An absolute geometry path outside the project must be rejected.");
    if (untouched.robotName != "untouched" || error.trimmed ().isEmpty ())
        return fail ("Rejected portable conversion must preserve output and report an error.");

    rws::RobotModelSpec portable;
    portable.robotName = "escape";
    drawable.filePath = "../outside.stl";
    portable.drawables = {drawable};
    rws::RobotModelSpec unresolved;
    unresolved.robotName = "untouched";
    error.clear ();
    if (rws::RobotModelProjectPaths::resolveManaged (
            portable, project.path (), unresolved, &error))
        return fail ("A relative geometry path that escapes the project must be rejected.");
    if (unresolved.robotName != "untouched" || error.trimmed ().isEmpty ())
        return fail ("Rejected managed resolution must preserve output and report an error.");
    return 0;
}

static int testManagedProjectGeometryRejectsEscapeThroughLinkedAncestor ()
{
    QTemporaryDir workspace;
    if (!workspace.isValid ())
        return fail ("Could not create a temporary workspace for linked path testing.");
    const QString projectRoot = workspace.filePath ("project");
    const QString outsideRoot = workspace.filePath ("outside");
    const QString linkedAssets = QDir (projectRoot).filePath ("linked-assets");
    if (!QDir ().mkpath (projectRoot) || !QDir ().mkpath (outsideRoot))
        return fail ("Could not create linked path test directories.");

#ifdef Q_OS_WIN
    QProcess linkProcess;
    linkProcess.setStandardOutputFile (QProcess::nullDevice ());
    linkProcess.setStandardErrorFile (QProcess::nullDevice ());
    linkProcess.start (
        QStringLiteral ("cmd.exe"),
        QStringList () << QStringLiteral ("/d") << QStringLiteral ("/c")
                       << QStringLiteral ("mklink") << QStringLiteral ("/J")
                       << QDir::toNativeSeparators (linkedAssets)
                       << QDir::toNativeSeparators (outsideRoot));
    if (!linkProcess.waitForFinished () || linkProcess.exitCode () != 0)
        return fail ("Could not create a directory junction for linked path testing.");
#else
    if (!QFile::link (outsideRoot, linkedAssets))
        return fail ("Could not create a directory symlink for linked path testing.");
#endif

    rws::RobotModelSpec portable;
    portable.robotName = "linked-escape";
    rws::DrawableSpec drawable;
    drawable.shape = "Mesh";
    drawable.filePath = "linked-assets/not-created/mesh.stl";
    portable.drawables = {drawable};
    rws::RobotModelSpec unresolved;
    unresolved.robotName = "untouched";
    QString error;
    const bool resolved = rws::RobotModelProjectPaths::resolveManaged (
        portable, projectRoot, unresolved, &error);
    QDir (projectRoot).rmdir (QStringLiteral ("linked-assets"));
    if (resolved)
        return fail ("A nonexistent geometry path below an outside-project link must be rejected.");
    if (unresolved.robotName != "untouched" || error.trimmed ().isEmpty ())
        return fail ("Rejected linked geometry resolution must preserve output and report an error.");
    return 0;
}

int main (int, char**)
{
    if (const int rc = testFullRoundTrip ())
        return rc;
    if (const int rc = testLegacyCollisionMetadataIsDiscardedOnSave ())
        return rc;
    if (const int rc = testDhAuthorityFlagIsPersistedAndLegacyDefaultsToFalse ())
        return rc;
    if (const int rc = testFingerprint ())
        return rc;
    if (const int rc = testManagedProjectGeometryPathsArePortable ())
        return rc;
    if (const int rc = testManagedProjectGeometryRejectsEscapes ())
        return rc;
    if (const int rc = testManagedProjectGeometryRejectsEscapeThroughLinkedAncestor ())
        return rc;
    std::cout << "RobotModelSpecJson round trip test passed." << std::endl;
    return 0;
}
