#include "RobotModelSpecProjectionAdapter.hpp"

#include <rw/math/RPY.hpp>
#include <rw/math/Rotation3D.hpp>
#include <rw/math/Constants.hpp>

#include <cmath>
#include <algorithm>
#include <map>

namespace rws {
namespace {

void addError(RobotModelSpecProjectionResult& result, const std::string& code,
              const std::string& fieldPath, const std::string& message)
{
    StructureOptimizationDiagnostic diagnostic;
    diagnostic.code = code;
    diagnostic.severity = "Error";
    diagnostic.subsystem = "structure-optimizer";
    diagnostic.stage = "robot-model-spec-projection";
    diagnostic.fieldPath = fieldPath;
    diagnostic.message = message;
    result.diagnostics.push_back(diagnostic);
}

bool sameTransform(const rw::math::Transform3D<>& first,
                   const rw::math::Transform3D<>& second)
{
    if ((first.P() - second.P()).norm2() > 1e-24)
        return false;
    for (std::size_t row = 0; row < 3; ++row)
        for (std::size_t column = 0; column < 3; ++column)
            if (std::fabs(first.R()(row, column) - second.R()(row, column)) > 1e-12)
                return false;
    return true;
}

void assignPose(const rw::math::Transform3D<>& transform,
                std::array< double, 3 >& position,
                std::array< double, 3 >& rpyDeg)
{
    const rw::math::RPY<> rpy(transform.R());
    position = {{transform.P()(0), transform.P()(1), transform.P()(2)}};
    static const double radToDeg = 180.0 / rw::math::Pi;
    rpyDeg = {{rpy(0) * radToDeg, rpy(1) * radToDeg, rpy(2) * radToDeg}};
}

bool isZAxis(const rw::math::Vector3D<>& axis)
{
    return std::fabs(axis(0)) < 1e-12 && std::fabs(axis(1)) < 1e-12 &&
           std::fabs(axis(2) - 1.0) < 1e-12;
}

std::string jointType(CanonicalJointType type)
{
    switch (type) {
    case CanonicalJointType::Revolute: return "Revolute";
    case CanonicalJointType::Prismatic: return "Prismatic";
    case CanonicalJointType::Fixed: return "FixedFrame";
    }
    return "Unknown";
}

std::string geometryShape(CanonicalGeometryKind kind)
{
    switch (kind) {
    case CanonicalGeometryKind::Cylinder: return "Cylinder";
    case CanonicalGeometryKind::Box: return "Box";
    case CanonicalGeometryKind::Tube: return "Cylinder";
    case CanonicalGeometryKind::Mesh: return "Mesh";
    case CanonicalGeometryKind::Unknown: default: return "Unknown";
    }
}

bool chainContainsFrame(const CanonicalKinematicModel& model, const DeviceChain& chain,
                        const std::string& frameId)
{
    if (chain.rootFrameId == frameId)
        return true;
    for (const std::string& jointId : chain.orderedJointIds) {
        for (const JointEdge& joint : model.joints) {
            if (joint.id == jointId && joint.childFrameId == frameId)
                return true;
        }
    }
    return false;
}

template< class Binding >
void assignGeometry(const Binding& binding, DrawableSpec& drawable)
{
    drawable.name = binding.id;
    drawable.refFrame = binding.referenceFrameId;
    drawable.shape = geometryShape(binding.kind);
    drawable.filePath = binding.sourceObjectId;
    drawable.dimensions = {{binding.width, binding.height, binding.depth}};
    drawable.radius = binding.radius;
    drawable.length = binding.length;
    assignPose(binding.referenceToGeometry, drawable.pos, drawable.rpyDeg);
    drawable.autoGenerated = false;
}

template< class Binding >
void assignCollision(const Binding& binding, CollisionModelSpec& collision)
{
    collision.name = binding.id;
    collision.refFrame = binding.referenceFrameId;
    collision.shape = geometryShape(binding.kind);
    collision.filePath = binding.sourceObjectId;
    collision.dimensions = {{binding.width, binding.height, binding.depth}};
    collision.radius = binding.radius;
    collision.length = binding.length;
    assignPose(binding.referenceToGeometry, collision.pos, collision.rpyDeg);
    collision.enabled = true;
}

}    // namespace

RobotModelSpecProjectionResult RobotModelSpecProjectionAdapter::project(
    const RobotModelSpecProjectionRequest& request)
{
    RobotModelSpecProjectionResult result;
    if (request.model == nullptr) {
        addError(result, "S38_PROJECTION_MODEL_REQUIRED", "model",
                 "A canonical model is required for RobotModelSpec projection.");
        return result;
    }
    const CanonicalKinematicModel& model = *request.model;
    const CanonicalKinematicModelValidationResult validation =
        CanonicalKinematicModelValidator::validate(model);
    if (!validation.valid) {
        result.diagnostics = validation.diagnostics;
        return result;
    }

    const auto chainIt = std::find_if(model.deviceChains.begin(), model.deviceChains.end(),
                                      [&model](const DeviceChain& chain) {
                                          return chain.id == model.activeDeviceChainId;
                                      });
    if (chainIt == model.deviceChains.end()) {
        addError(result, "S38_PROJECTION_ACTIVE_CHAIN_MISSING", "activeDeviceChainId",
                 "The canonical active device chain is required for projection.");
        return result;
    }
    std::map< std::string, const JointEdge* > joints;
    for (const JointEdge& joint : model.joints)
        joints[joint.id] = &joint;
    std::map< std::string, CanonicalFrameType > frameTypes;
    for (const FrameNode& frame : model.frames)
        frameTypes[frame.id] = frame.type;

    RobotModelSpec spec;
    if (request.sourceSnapshot != nullptr)
        spec = *request.sourceSnapshot;
    spec.robotName = request.robotName.empty() ? model.modelId : request.robotName;
    if (spec.robotName.empty())
        spec.robotName = "CanonicalCandidate";
    spec.saveDirectory = request.saveDirectory;
    spec.mode = KinematicsViewMode::JointRPYPos;
    spec.exportDhJointsAdvanced = false;
    spec.dhJoints.clear();
    spec.generateScene = true;
    spec.generateDrawables = true;
    spec.transformJoints.clear();
    spec.limits.clear();
    spec.poses.clear();

    if (model.baseFrameId != "Base") {
        addError(result, "S38_PROJECTION_BASE_NAME_UNSUPPORTED", "baseFrameId",
                 "The evaluation RobotModelSpec contract requires the canonical device base to be named Base.");
        return result;
    }

    std::size_t firstEdge = 0;
    if (chainIt->rootFrameId != model.baseFrameId) {
        rw::math::Transform3D<> rootToBase;
        bool foundBase = false;
        for (; firstEdge < chainIt->orderedJointIds.size(); ++firstEdge) {
            const JointEdge& baseEdge = *joints.at(chainIt->orderedJointIds[firstEdge]);
            if (baseEdge.type != CanonicalJointType::Fixed) {
                addError(result, "S38_PROJECTION_BASE_EDGE_INVALID", "deviceChains.active",
                         "All root-to-Base installation edges must be fixed.");
                return result;
            }
            rootToBase = rootToBase * baseEdge.parentToJointZero * baseEdge.jointMotionToChild;
            if (baseEdge.childFrameId == model.baseFrameId) {
                foundBase = true;
                break;
            }
        }
        if (!foundBase) {
            addError(result, "S38_PROJECTION_BASE_EDGE_MISSING", "deviceChains.active",
                     "A chain rooted outside Base must contain a root-to-Base fixed edge.");
            return result;
        }
        spec.robotBaseFrame.name = "RobotBase";
        spec.robotBaseFrame.refFrame = "WORLD";
        spec.robotBaseFrame.frameType = SceneFrameType::Fixed;
        assignPose(rootToBase, spec.robotBaseFrame.pos, spec.robotBaseFrame.rpyDeg);
        ++firstEdge;
    }
    else {
        spec.robotBaseFrame.name = "RobotBase";
        spec.robotBaseFrame.refFrame = "WORLD";
        spec.robotBaseFrame.frameType = SceneFrameType::Fixed;
        spec.robotBaseFrame.pos = {{0.0, 0.0, 0.0}};
        spec.robotBaseFrame.rpyDeg = {{0.0, 0.0, 0.0}};
    }

    for (std::size_t index = firstEdge; index < chainIt->orderedJointIds.size(); ++index) {
        const JointEdge& edge = *joints.at(chainIt->orderedJointIds[index]);
        if (edge.type != CanonicalJointType::Fixed && !isZAxis(edge.motionAxisInJoint)) {
            addError(result, "S38_PROJECTION_AXIS_UNSUPPORTED", "joints[" + edge.id + "].motionAxisInJoint",
                     "The legacy evaluation XML contract supports only the canonical local Z joint axis.");
            return result;
        }
        if (edge.type != CanonicalJointType::Fixed && !sameTransform(edge.jointMotionToChild,
                                                                       rw::math::Transform3D<>())) {
            addError(result, "S38_PROJECTION_POST_MOTION_UNSUPPORTED", "joints[" + edge.id + "].jointMotionToChild",
                     "A movable canonical edge with a post-motion transform cannot be represented losslessly by the legacy XML joint.");
            return result;
        }

        JointTransformSpec projected;
        projected.name = edge.childFrameId;
        projected.type = jointType(edge.type);
        const auto childType = frameTypes.find(edge.childFrameId);
        if (childType != frameTypes.end() && childType->second == CanonicalFrameType::Tool)
            projected.type = "ToolFrame";
        rw::math::Transform3D<> zero = edge.parentToJointZero * edge.jointMotionToChild;
        if (edge.type == CanonicalJointType::Revolute && edge.zeroPositionOffset != 0.0)
            zero = edge.parentToJointZero * rw::math::Transform3D<>(
                rw::math::Rotation3D<>(rw::math::RPY<>(0.0, 0.0, edge.zeroPositionOffset))) *
                edge.jointMotionToChild;
        else if (edge.type == CanonicalJointType::Prismatic && edge.zeroPositionOffset != 0.0)
            zero = edge.parentToJointZero * rw::math::Transform3D<>(
                edge.motionAxisInJoint * edge.zeroPositionOffset) * edge.jointMotionToChild;
        assignPose(zero, projected.pos, projected.rpyDeg);
        spec.transformJoints.push_back(projected);

        if (edge.type != CanonicalJointType::Fixed && edge.physicalLimits.enabled) {
            JointLimitSpec limit;
            limit.jointName = edge.childFrameId;
            const double scale = edge.physicalLimits.unit == CanonicalCoordinateUnit::Radians
                                     ? (180.0 / rw::math::Pi) : 1.0;
            limit.posMin = edge.physicalLimits.lower * scale;
            limit.posMax = edge.physicalLimits.upper * scale;
            // RobotModelSpec requires positive dynamic limits even though the
            // canonical evaluation contract does not model velocity/acceleration.
            limit.velMax = 1.0;
            limit.accMax = 1.0;
            spec.limits.push_back(limit);
        }
    }

    // A canonical tool may be represented as a binding outside the device
    // chain.  Project it as an explicit ToolFrame so the legacy writer keeps
    // the authored flange-to-TCP transform instead of inventing a zero TCP.
    for (const ToolBinding& tool : model.toolBindings) {
        if (chainContainsFrame(model, *chainIt, tool.tcpFrameId))
            continue;
        if (tool.flangeFrameId.empty() || tool.tcpFrameId.empty()) {
            addError(result, "S38_PROJECTION_TOOL_BINDING_INVALID", "toolBindings",
                     "Tool bindings require non-empty flange and TCP frame IDs.");
            return result;
        }
        if (tool.flangeFrameId != chainIt->tipFrameId) {
            addError(result, "S38_PROJECTION_TOOL_PARENT_UNSUPPORTED", "toolBindings[" + tool.id + "]",
                     "A ToolBinding outside the chain tip cannot be represented by the legacy serial-device output.");
            return result;
        }
        JointTransformSpec projected;
        projected.name = tool.tcpFrameId;
        projected.type = "ToolFrame";
        assignPose(tool.flangeToTcp, projected.pos, projected.rpyDeg);
        spec.transformJoints.push_back(projected);
    }

    PoseSpec zero;
    zero.name = "CanonicalZero";
    zero.q.assign(model.dofs.size(), 0.0);
    spec.poses.push_back(zero);

    spec.drawables.clear();
    for (const GeometryBinding& binding : model.geometryBindings) {
        DrawableSpec drawable;
        assignGeometry(binding, drawable);
        spec.drawables.push_back(drawable);
    }
    spec.collisionModels.clear();
    for (const CollisionBinding& binding : model.collisionBindings) {
        CollisionModelSpec collision;
        assignCollision(binding, collision);
        spec.collisionModels.push_back(collision);
    }

    result.ok = true;
    result.spec = spec;
    return result;
}

}    // namespace rws
